openapi: 3.0.0
info:
  version: 0.1.0
  title: Deploy Swagger to Amplify Hosting
  description: >-
    Deploy Swagger to Amplify Hosting
servers:
  - url: 'http://petstore.swagger.io/api'
paths:
  /hoge:
    get:
      description: >
        hogehoge
      responses:
        '200':
          description: hoge response
          content:
            application/json:
              schema:
                type: "object"
                description: "hogeのレスポンス"
                properties:
                  id:
                    type: "integer"
                    format: "int64"
                  name:
                    type: "string"
                    example: "test"